- name: "Check if there is a Jenkins container running"
  shell: "docker ps | awk '{print $NF}' | grep jenkins"
  register: check_jenkins
  ignore_errors: True

- name: "Pull Jenkins"
  shell: "docker pull orchardup/jenkins"
  when: check_jenkins.stdout != "jenkins"
  
- name: "Start Jenkins container"
  shell: "docker run --name jenkins -d -p 80:8080 orchardup/jenkins"
  when: check_jenkins.stdout  != "jenkins"
