---
- name: set OS to RHEL7 compatible
  set_fact: os_version="el7"
  when: ansible_os_family=="RedHat" and ansible_distribution_major_version=="7"

# include mysql vars here, because user/pass is also used to configure
# zabbix web and server, not just fir mysql
- include_vars: mysql_vars.yml
- include_vars: zabbix-server.yml

- include: mysql_server.yml

- include: httpd.yml

- name: install mysql client
  package: name=mysql state=latest update_cache=yes

- include: php.yml

- name: zabbix 3.2 yum repo
  yum: name=http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm
      state=present
  when: os_version=="el7"

- name: zabbix-server-mysql package
  yum: name=zabbix-server-mysql state=latest update_cache=yes
  notify: restart zabbix-server

- name: zabbix-web-mysql package
  package: name=zabbix-web-mysql state=latest update_cache=yes
  notify: restart httpd

#- name: set php timezone
- lineinfile: dest=/etc/httpd/conf.d/zabbix.conf
      regexp='^        \# php_value date.timezone Europe/Riga$'
      line='        php_value date.timezone Europe/London'
      backrefs=yes
  notify: restart httpd

- name: /etc/zabbix/web/zabbix.conf.php
  template: src=zabbix.conf.php.j2 dest=/etc/zabbix/web/zabbix.conf.php
      owner=apache group=apache mode=0640
  notify: restart httpd

- name: /etc/zabbix/zabbix_server.conf
  template: src=zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf
      owner=root group=root mode=0644
  notify: restart zabbix-server

- name: zabbix-server daemon
  service: name=zabbix-server enabled=yes
