- name: "Copy Dockerfile and api file to /tmp"
  copy: src={{ item }} dest=/tmp/{{ item }}
    owner=root group=root mode=0644
  with_items: 
    - Dockerfile
    - api.py
    
- name: "Check if there is an application container running"
  shell: "docker ps | awk '{print $NF}' | grep my-app"
  register: check_app
  ignore_errors: True
    
- name: "Build app container"
  shell: "cd /tmp && docker build -t centos:6.8 ."
  when: check_app.stdout != "my-app"
  
- name: "Start app container"
  shell: "docker run -dit --name my-app -p 5000:5000 centos:6.8"
  when: check_app.stdout != "my-app"